---
apiVersion: v1
kind: Namespace
metadata:
  name: mygame
  labels:
    app: '2048'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygame
  namespace: mygame
  labels:
    app: '2048'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: '2048'
      env: dev
  template:
    metadata:
      labels:
        app: '2048'
        env: dev
    spec:
      containers:
      - name: game-2048 
        image: chukmunnlee/2048:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

