# ---
# # imperative command 
# # kubectl create ns workshop
# # create a namespace
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: geekshacking
#   labels:
#     env: workshop

---
# create a configmap, 
apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo
  namespace: geekshacking
data:
  PODINFO_UI_MESSAGE: 'hello, world!'

---
# create a pod, give it a name, add the geekshacking namespace
# add some labels
apiVersion: v1
kind: Pod
metadata:
  name: podinfo
  namespace: geekshacking
  labels:
    env: worksho8
spec:
  containers:
  - name: podinfo-container
    image: stefanprodan/podinfo:6.14.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 9898
    envFrom:
    - configMapRef:
        name: podinfo # cm podinfo
